FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY web_vendor /usr/share/nginx/html/web_vendor

RUN mkdir -p /usr/share/nginx/html/data /tmp/nginx_dav

EXPOSE 80
